{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: {{ include "pod-deletion-cost-controller.fullname" . }}
    labels:
    {{- include "pod-deletion-cost-controller.labels" . | nindent 4 }}
subjects:
    - kind: ServiceAccount
      name: {{ include "pod-deletion-cost-controller.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
roleRef:
    kind: ClusterRole
    name: {{ include "pod-deletion-cost-controller.fullname" . }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
